/**
 * Constants Index
 *
 * Re-exports all viewer constants
 */

export {
  // Zoom settings
  MIN_ZOOM,
  MAX_ZOOM,
  DEFAULT_ZOOM,
  ZOOM_STEP,
  WHEEL_ZOOM_SPEED,
  DRAG_ZOOM_DENOMINATOR,
  DRAG_ZOOM_SPEED,
  // Scroll settings
  WHEEL_SCROLL_THRESHOLD,
  WHEEL_MAX_SLICE_STEP,
  // Cine settings
  DEFAULT_CINE_FPS,
  MIN_CINE_FPS,
  MAX_CINE_FPS,
  // Cache settings
  MAX_IMAGE_CACHE,
  PRELOAD_AHEAD_PLAYING,
  PRELOAD_AHEAD_PAUSED,
  PRELOAD_BEHIND,
  US_PRELOAD_MULTIPLIER,
  // Window/Level
  WINDOW_LEVEL_PRESETS,
  DEFAULT_WINDOW_LEVEL,
  getWindowLevelPresets,
  getDefaultWindowLevel,
  type WindowLevelPreset,
  // Measurement settings
  HIT_TEST_TOLERANCE,
  POLYGON_CLOSE_THRESHOLD,
  MIN_VERTEX_DISTANCE,
  FREEHAND_SAMPLE_INTERVAL,
  MAX_UNDO_HISTORY,
  MEASUREMENT_COLORS,
  COLOR_PALETTE,
  // UI settings
  SNACKBAR_DURATION,
  TOOLTIP_DELAY,
  PANEL_WIDTHS,
  ANIMATION_DURATIONS,
  // AI settings
  AI_OVERLAY_OPACITY,
  DETECTION_STROKE_WIDTH,
  DETECTION_LABEL_FONT_SIZE,
  // 3D settings
  MPR_CROSSHAIR_COLOR,
  MPR_DEFAULT_THICKNESS,
  // Keyboard shortcuts
  KEYBOARD_SHORTCUTS,
} from './viewer.constants';
